# create courses table
CREATE TABLE `courses` (
  `course_name` varchar(100) NOT NULL DEFAULT '',
  `tee` varchar(20) NOT NULL,
  `rating` decimal(3,1) NOT NULL,
  `slope` tinyint(3) unsigned NOT NULL,
  `hole1` smallint(5) unsigned NOT NULL,
  `hole2` smallint(5) unsigned NOT NULL,
  `hole3` smallint(5) unsigned NOT NULL,
  `hole4` smallint(5) unsigned NOT NULL,
  `hole5` smallint(5) unsigned NOT NULL,
  `hole6` smallint(5) unsigned NOT NULL,
  `hole7` smallint(5) unsigned NOT NULL,
  `hole8` smallint(5) unsigned NOT NULL,
  `hole9` smallint(5) unsigned NOT NULL,
  `hole10` smallint(5) unsigned NOT NULL,
  `hole11` smallint(5) unsigned NOT NULL,
  `hole12` smallint(5) unsigned NOT NULL,
  `hole13` smallint(5) unsigned NOT NULL,
  `hole14` smallint(5) unsigned NOT NULL,
  `hole15` smallint(5) unsigned NOT NULL,
  `hole16` smallint(5) unsigned NOT NULL,
  `hole17` smallint(5) unsigned NOT NULL,
  `hole18` smallint(5) unsigned NOT NULL,
  PRIMARY KEY (`course_name`,`tee`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

# create scores table
CREATE TABLE `scores` (
  `course_name` varchar(100) NOT NULL,
  `tee` varchar(20) NOT NULL,
  `hole1` tinyint unsigned NOT NULL,
  `hole1putts` tinyint unsigned,
  `hole1fairway` varchar(5),
  `hole1penalty_strokes` tinyint unsigned,
  `hole1sand_shots` tinyint unsigned,
  `hole2` tinyint unsigned NOT NULL,
  `hole2putts` tinyint unsigned,
  `hole2fairway` varchar(5),
  `hole2penalty_strokes` tinyint unsigned,
  `hole2sand_shots` tinyint unsigned,
  `hole3` tinyint unsigned NOT NULL,
  `hole3putts` tinyint unsigned,
  `hole3fairway` varchar(5),
  `hole3penalty_strokes` tinyint unsigned,
  `hole3sand_shots` tinyint unsigned,
  `hole4` tinyint unsigned NOT NULL,
  `hole4putts` tinyint unsigned,
  `hole4fairway` varchar(5),
  `hole4penalty_strokes` tinyint unsigned,
  `hole4sand_shots` tinyint unsigned,
  `hole5` tinyint unsigned NOT NULL,
  `hole5putts` tinyint unsigned,
  `hole5fairway` varchar(5),
  `hole5penalty_strokes` tinyint unsigned,
  `hole5sand_shots` tinyint unsigned,
  `hole6` tinyint unsigned NOT NULL,
  `hole6putts` tinyint unsigned,
  `hole6fairway` varchar(5),
  `hole6penalty_strokes` tinyint unsigned,
  `hole6sand_shots` tinyint unsigned,
  `hole7` tinyint unsigned NOT NULL,
  `hole7putts` tinyint unsigned,
  `hole7fairway` varchar(5),
  `hole7penalty_strokes` tinyint unsigned,
  `hole7sand_shots` tinyint unsigned,
  `hole8` tinyint unsigned NOT NULL,
  `hole8putts` tinyint unsigned,
  `hole8fairway` varchar(5),
  `hole8penalty_strokes` tinyint unsigned,
  `hole8sand_shots` tinyint unsigned,
  `hole9` tinyint unsigned NOT NULL,
  `hole9putts` tinyint unsigned,
  `hole9fairway` varchar(5),
  `hole9penalty_strokes` tinyint unsigned,
  `hole9sand_shots` tinyint unsigned,
  `hole10` tinyint unsigned NOT NULL,
  `hole10putts` tinyint unsigned,
  `hole10fairway` varchar(5),
  `hole10penalty_strokes` tinyint unsigned,
  `hole10sand_shots` tinyint unsigned,
  `hole11` tinyint unsigned NOT NULL,
  `hole11putts` tinyint unsigned,
  `hole11fairway` varchar(5),
  `hole11penalty_strokes` tinyint unsigned,
  `hole11sand_shots` tinyint unsigned,
  `hole12` tinyint unsigned NOT NULL,
  `hole12putts` tinyint unsigned,
  `hole12fairway` varchar(5),
  `hole12penalty_strokes` tinyint unsigned,
  `hole12sand_shots` tinyint unsigned,
  `hole13` tinyint unsigned NOT NULL,
  `hole13putts` tinyint unsigned,
  `hole13fairway` varchar(5),
  `hole13penalty_strokes` tinyint unsigned,
  `hole13sand_shots` tinyint unsigned,
  `hole14` tinyint unsigned NOT NULL,
  `hole14putts` tinyint unsigned,
  `hole14fairway` varchar(5),
  `hole14penalty_strokes` tinyint unsigned,
  `hole14sand_shots` tinyint unsigned,
  `hole15` tinyint unsigned NOT NULL,
  `hole15putts` tinyint unsigned,
  `hole15fairway` varchar(5),
  `hole15penalty_strokes` tinyint unsigned,
  `hole15sand_shots` tinyint unsigned,
  `hole16` tinyint unsigned NOT NULL,
  `hole16putts` tinyint unsigned,
  `hole16fairway` varchar(5),
  `hole16penalty_strokes` tinyint unsigned,
  `hole16sand_shots` tinyint unsigned,
  `hole17` tinyint unsigned NOT NULL,
  `hole17putts` tinyint unsigned,
  `hole17fairway` varchar(5),
  `hole17penalty_strokes` tinyint unsigned,
  `hole17sand_shots` tinyint unsigned,
  `hole18` tinyint unsigned NOT NULL,
  `hole18putts` tinyint unsigned,
  `hole18fairway` varchar(5),
  `hole18penalty_strokes` tinyint unsigned,
  `hole18sand_shots` tinyint unsigned,
  INDEX (`course_name`,`tee`),
  FOREIGN KEY (`course_name`,`tee`) REFERENCES courses(`course_name`,`tee`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
